name: mrt
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  # pie_chart: ^5.1.0
  syncfusion_flutter_charts: ^19.1.54
  http: ^0.13.4
  table_calendar: ^3.0.4
  flutter_secure_storage: ^5.0.2
  syncfusion_flutter_calendar: ^19.4.54
  async: ^2.8.2
  cupertino_icons: ^1.0.2
  getwidget: ^2.0.5
  syncfusion_flutter_datagrid: ^19.1.69-beta
  dropdown_search: ^2.0.1
  date_field: ^3.0.0
  provider: ^4.0.2
  flutter_speed_dial: ^5.0.0+1
  dropdown_button2: ^1.2.2 
  flutter_datetime_picker: ^1.5.1
  snippet_coder_utils: ^1.0.12
  accordion: ^2.2.3
  flutter_spinkit: ^5.1.0
  fl_chart: ^0.46.0
  infinite_carousel: ^1.0.2
  syncfusion_flutter_xlsio: ^19.4.56-beta
  excel: 2.0.0-null-safety
  # excel: 2.0.0-null-safety
  # create pdf document
  pdf: ^3.1.0
  file_picker: ^3.0.3
  # save file
  path_provider: ^2.0.1

  # open pdf document
  open_file: ^3.1.0
  syncfusion_flutter_datagrid_export: ^19.4.56-beta
  universal_html: ^2.0.8
  liquid_progress_indicator: ^0.4.0
  barcode_widget: ^2.0.2
  flutter_barcode_scanner: ^2.0.0
  flutter_downloader: ^1.7.3
  permission_handler: ^9.2.0
  
dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo MRT.png"
    
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logolarge.png
    - assets/images/Logo JAK.png
    - assets/images/Logo MRT.png
    - assets/fruit.svg
    - assets/person.jpg


  